### ISSUE TITLE
Attemting to add "Cycle" option to gamepad crashes application.

### ISSUE THREAD

**Issue by c-d0wd** [bwRavencl/ControllerBuddy#150]
Steps taken:
- Selected Left Bumper
- Added a "Cycle" Action
- Edit Actions
- Add vJoy Button Input
- Crash

Output:
> java.lang.NullPointerException:``` Cannot invoke "de.bwravencl.controllerbuddy.input.Profile.getModes()" because "this.unsavedProfile" is null

Full exception output:
[Crash.txt](https://github.com/bwRavencl/ControllerBuddy/files/13806185/Crash.txt)

**Comment by bwRavencl** [comment]
Thanks a lot for reporting @c-d0wd!  
Should be fixed now.
