### ISSUE TITLE
"There is no controller connected."

### ISSUE THREAD

**Issue by stoopedm** [bwRavencl/ControllerBuddy#5]
Hello. I'm trying to run ControllerBuddy 0.12.34 on Windows 10 with vJoy v2.1.9 installed, but when I run it I get the "There is no controller connected. Without a controller ControllerBuddy can only be used in client-mode." message. There is one device in vJoy configuration and examples that come with it seem to work Ok (feeder/monitor programs). I've tried adding another device and resetting devices in configuration, but nothing changed. What could be the problem?

**Comment by stoopedm** [comment]
I also use Oracle JRE 8 update 231, if that matters.

**Comment by bwRavencl** [comment]
Hello @stoopedm!

The message indicates that ControllerBuddy cannot find any physical controller (i.e. gamepad).

The following questions arise:
- Which Operating System are you running?
- Do you have a gamepad connected?
- And if so which exact model is it?
- Can you please provide the ControllerBuddy.log file that should be located under your Temp folder. On Windows it should be under: `C:\Users\YOUR_USERNAME\AppData\Local\Temp\ControllerBuddy.log`

> I also use Oracle JRE 8 update 231, if that matters.

If you are using the binaries from the Release page ControllerBuddy will not use any JRE installed on your system but use its own integrated (minimal) JRE.

**Comment by stoopedm** [comment]
Oh, actually there is no problem. Sorry. I was in a hurry and just misunderstood what ControllerBuddy purpose is, I thought it would be able to configure only a virtual joystick device.
