### ISSUE TITLE
Only physical controllers supported?

### ISSUE THREAD

**Issue by JabberwockPL** [bwRavencl/ControllerBuddy#6]
I need to send data over network from one instance of FreePIE (https://andersmalmgren.github.io/FreePIE/)  to another. As FreePIE supports writing to vJoy, I have figured I will feed data to one vJoycontroller on one end, send it over with ControllerBuddy and then recover it from vJoy on the other end.

However, when I start ControllerBuddy on the 'sender' computer, it says that no controller is connected (i.e. it does not detect the vJoy controller)... Is it only for physical controllers? I realize that it might be done on purpose (to avoid endless loops), but there might be other ways around that...

**Comment by bwRavencl** [comment]
Hi @JabberwockPL !
ControllerBuddy only supports gamepads as source input devices.
Specifically all gamepads supported by the [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) project can be used with ControllerBuddy.
